### PR TITLE
feat: Ory Cloud Landing

### PR DESCRIPTION
**Pull request by vinckr**
Continuation of the old PR https://github.com/ory/web/pull/476/files

### CODE REVIEW

**Review by zeropaper — COMMENTED** [review]
@vinckr 

The code looks OK and a brief look at the preview deployment as well.

Just to be sure.
It adds a new page (`/cloud`), there's no need for a redirection?

**Comment by vinckr** [comment]
> @vinckr
> 
> The code looks OK and a brief look at the preview deployment as well.
> 
> Just to be sure. It adds a new page (`/cloud`), there's no need for a redirection?

Thanks for the review! 
There might be some kinks (espc images) we still need to iron out though. 

I dont think we need a redirect, and yes the main focus of this PR is to add ory.sh/cloud :-)

**Comment by vinckr** [comment]
@jfcurran @BlueAcidFrog 
Done from my side!

**Comment by vinckr** [comment]
Screenshot 2022-01-20 at 14 14 54

Fixed all the links.

The performance on mobile in lighthouse is suddenly around 80 since the last commit, can you confirm that this is only on my end @zeropaper ?

**Review by BlueAcidFrog — DISMISSED** [review]

**Comment by BlueAcidFrog** [comment]
LGTM

**Comment by zeropaper** [comment]
@vinckr honestly, this is one of the best scores I've seen in a very long time... and the it's not the performance but the SEO score that seems around 75%/80%

Lighthouse doesn't know that this is a preview page and has a false positive on the canonical URL... you can forget about that :)

There's also a directive that is also used, most likely, in netlify preview (x-robots-tag: noindex) that grinds down the score...

image

The only things Lighthouse complains about and are relevant are links without descriptive texts...

**Review by zeropaper — DISMISSED** [review]
:+1:

**Comment by BlueAcidFrog** [comment]
@jfcurran, are we good to merge?

**Comment by jfcurran** [comment]
Technically yes - but I see that the hero copy on landing is too wide for mobile screens. Over all pretty good

**Review by zeropaper — APPROVED** [review]
:+1:

**Comment by jfcurran** [comment]
Screenshot 2022-01-21 at 13 51 24
I think this should not be here - is this part of netlify cms? 

Steps to reproduce:  
- site without stuff stored in cache
- hit accept on first banner
- visit products / ory cloud
- be asked to accept something

**Comment by MicLeey** [comment]
I was able to reproduce this on the liv site - so it shouldn't be a blocker for this to be merged.

I will log an issue tracking the double consent separately

**Comment by aeneasr** [comment]
@BlueAcidFrog @zeropaper the banner is coming from hubspot

**Comment by BlueAcidFrog** [comment]
fixed, can we merge this?

**Comment by vinckr** [comment]
@zeropaper @jfcurran 
can i has merge 🙏

**Comment by zeropaper** [comment]
> @zeropaper @jfcurran can i has merge pray

unfortunately, they are merge conflicts, but from my side :+1:

**Comment by vinckr** [comment]
Hm I dont see conflicts on my side? 
What can I do to fix them?

**Comment by BlueAcidFrog** [comment]
can we merge please?

**Comment by zeropaper** [comment]
That's what I usually do:

1. `git stash` (if I have uncommited changes)
2. `git checkout master`
3. `git pull`
4. `git checkout <branch_name>`
5. `git rebase master`
6. fix the conflicts - follow instructions from Git
7. `git push --force origin <branch_name>`

**Review by zeropaper — APPROVED** [review]

**Review by BlueAcidFrog — APPROVED** [review]

**Pull request merged**
