### PR TITLE
fix: requirements list in section 2.2C

### PR DESCRIPTION
**Pull request by jaredpreston**
Fix the list of requirements in section 2.2c of the Preview Terms of Service Agreement. Was not rendering correctly.

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by jfcurran — APPROVED** [review]
👍

**Comment by zepatrik** [comment]
I am pretty sure this will not render properly as well, but as jared used his fork we have no netlify build to see it. Will open a new pr with his commit to see the changes.

**Comment by zepatrik** [comment]
See https://603cd426d579f1e3097c728b--wonderful-sinoussi-8532a7.netlify.app/ptos/
The problem is that indentation by four spaces is a codeblock in markdown: https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

**Comment by zepatrik** [comment]
Continued as #152

**Pull request closed without merging**
