### PR TITLE
fix: icon performance

### PR DESCRIPTION
**Pull request by Benehiko**
## Related issue

https://github.com/ory/web/issues/223

## Proposed changes

Swap out [phosphor-react](https://github.com/phosphor-icons/phosphor-react) with our own custom icon component. Phosphor react seems to be using inline-svg's instead of wrapping them inside images, this causes performance issues on our side.
This draft-pr proposes to swap it out and render the icons ourselves through `` tags. This, however, comes with its own set of problems, such as using css `filter` to change the icon colour. 

Checklist
- [x] Fix alignment inside buttons
- [x] Feat duo tone styling
- [X] Using `` element
- [X] Can style with `filter` using current theme variables

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Shit, that looks more complicated than I thought 😓

**Comment by Benehiko** [comment]
> Shit, that looks more complicated than I thought

Yeah we were using an npm library so I replaced it. 

For some reason the build is failing on the CI? I tried looking at what the cause is, but not quite sure what it could be.

**Comment by aeneasr** [comment]
idk, rerunning jobs

**Comment by aeneasr** [comment]
Does the build work locally for you?

**Comment by Benehiko** [comment]
> Does the build work locally for you?

`npm run develop` works
`npm run build` fails with a similar error to the CI - investigating it, but the error isn't clear

**Comment by aeneasr** [comment]
Nice :) The scores improved! You probably know this already, but the icons on open source are not yet in the right color: 
Bildschirmfoto 2021-06-08 um 13 53 28

about us:

Bildschirmfoto 2021-06-08 um 13 54 53

kratos/hydra/...

Bildschirmfoto 2021-06-08 um 13 55 40

And they're also not properly centered yet:

Bildschirmfoto 2021-06-08 um 13 56 13

The button icon:

Bildschirmfoto 2021-06-08 um 13 56 26

---

I didn't think this would be so much work...

But yeah the problem certainly is with SVGs inline we get styling and without them inline it's much harder...

You could also check out masks: https://stackoverflow.com/questions/24933430/img-src-svg-changing-the-styles-with-css

**Comment by Benehiko** [comment]
Yes :) 
Busy styling the icons now properly to match what we had. 
I did end up using a filter methodology (convert hex to filter values) inside the styled component which seem to be working well
https://github.com/ory/web/blob/c5f210b2113a700235c3db83c0ab32fa68759763/src/components/freestanding/colour/colour-wrapper.tsx#L58-L62

I just haven't gone through all the icons yet to add their correct colours.

**Comment by aeneasr** [comment]
Good job!

**Pull request merged**
