### PR TITLE
fix: move pricing in navigation

### PR DESCRIPTION
**Pull request by jfcurran**
-m

### CODE REVIEW

**Review by BlueAcidFrog — COMMENTED** [review]
changing position of pricing

**Review by BlueAcidFrog — DISMISSED** [review]
LGTM @vinckr

**Comment by vinckr** [comment]
You had a opening bracket missing @BlueAcidFrog , that is why the preview build failed. If that check fails its an indication that there is an error in the PR. Please make sure the preview build (and all other checks) are green, before approving!

You also removed the pricing from mobile navigation I assume that was in error. 

I fixed the build and added it back to the mobile nav again, please take a look at the preview and check all views ([tutorial how to view website in mobile](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome))

**Comment by BlueAcidFrog** [comment]
@vinckr thank you

**Pull request merged**
