### PR TITLE
fix: remove temporary redirect

### LINKED ISSUE #426: upstream reference closed: github.com/ory/web/pull/420
The upstream [pull](https://github.com/ory/web/pull/420) got closed. It is referenced in:
- [ ] [static/_redirects#L274](https://github.com/ory/web/blob/bbf96fe192d10f213f929c532d9651f43418eef3/static/_redirects#L274)

This issue was created by the [ORY Closed Reference Notifier](https://github.com/ory/closed-reference-notifier) GitHub action.

### PR DESCRIPTION
**Pull request by zepatrik**
closes #426
@MicLeey FIY, I added the redirect because on Friday the links in the youtube descriptions were resulting in 404.

### CODE REVIEW

**Comment by zepatrik** [comment]
And btw, why did no one notice that the page was not available after merging @MicLeey @BlueAcidFrog @jfcurran @vinckr ?

**Comment by MicLeey** [comment]
Not sure - this commit must've been undone at some point: https://github.com/ory/web/pull/420/commits/042ba6380209e52ccb961f488c67738db06dcb5e

**Comment by zepatrik** [comment]
Screenshot from 2021-11-14 21-30-38
It was included in the merge, but both redirects were there until now:
https://github.com/ory/web/blob/6a05348c9d3f282cc499971c78636275803cfc35/static/_redirects#L259-L275

**Comment by zepatrik** [comment]
I mean it is possible that you missed my commit, but then did you not checked if it works after you merged?

**Comment by MicLeey** [comment]
That's likely what happened yes. Was very late Friday night :)
Apologies - hadn't merged your commit into the summit branch so I assumed the redirects would do the trick

**Comment by zepatrik** [comment]
I guess one problem also is that the redirects don't affect the netlify previews.

**Comment by aeneasr** [comment]
> And btw, why did no one notice that the page was not available after merging

Very simple, because software is complex and we don't have any tests in this repository ensuring that redirects and links work. Humans can only review so much. Thank you for noticing though and fixing it!

**Pull request merged**
