### PR TITLE
Prettify everything

### PR DESCRIPTION
**Pull request by kevgo**
- update to ory-prettier-styles@1.3.0
- unleash Prettier to format all files it knows (now including for example YML)
- prettify all files in this repo
- no changes to the textual content of any files (except config files like package.json and .prettierignore)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
      vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
      maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments

This will cause merge conflicts in existing branches. I will go through all the ones with open pull requests and resolve them for you. If you want to resolve them yourself, and your branch was relatively up tod date, i.e. you encounter only formatting differences, choose the ["ours" version](https://howchoo.com/git/git-merge-conflicts-rebase-ours-theirs) in Git to keep your content and finish the merge or rebase. Then run `npm run format` to update the formatting.

### CODE REVIEW

**Review by kevgo — COMMENTED** [review]
I have done a cursory inspection of all files and the changes, although widespread, look safe.

**Review by jfcurran — APPROVED** [review]
Few things are as pleasing as consistently clean code 🙏  

I went through most layout components to check wether something broke, but all of this looks fine to me, works locally, and on the preview build. Eventually, adding tests with Jest and adding those tests to our jobs here will give us a lot of QoL, especially for changes like this one where +250 files get changed.

We ought to make sure our IDE is in sync with prettier so that we don't have unnecessary auto formatting happening @vinckr (although this now now longer matters for the codebase here on GitHub 🤠 )

**Comment by kevgo** [comment]
Yeah 💯 for installing the Prettier plugin into your IDE:

- https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
- https://www.jetbrains.com/help/idea/prettier.html

And configure them to prettify on save. This is when Prettier becomes a magical tool you can lean on during coding/writing, rather than an annoying thing you forget to run after coding.

**Comment by aeneasr** [comment]
@kevgo please keep conventional commits in mind when merging, thank you :)

**Comment by kevgo** [comment]
Argh!! I created #703 to automate teaching this new trick to old dogs like me 😆

**Pull request merged**
