### PR TITLE
feat: typography refactor

### PR DESCRIPTION
**Pull request by jfcurran**
I reworked some parts of how typography affects the look of our website:

- typography now has harmonic scale
- styling adheres to semantics on landing pages
- minor typography fixes across the board (stats, blog section, blog overview)
- adjust behaviour of our blog overview and touched up typography

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
Looking sweet!

**Comment by jfcurran** [comment]
@aeneasr ready to be squashed and merged at your behest

**Comment by aeneasr** [comment]
@jfcurran there were a couple of merge conflicts, could you check if your changes made it through as expected?

**Comment by jfcurran** [comment]
LGTM - coooool

**Comment by aeneasr** [comment]
😎

**Pull request merged**
