### PR TITLE
feat: embedd yt video

### PR DESCRIPTION
**Pull request by vinckr**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by Benehiko** [comment]
Just maybe my two cents about it - Since it covers the whole width of the screen, it feels a bit like it's breaking the flow of the website. Maybe we should just make the video a bit smaller with some "ory" styling around it. Can even be in a look similar to the `feature-image` component - Video on one side and text on the other. But if you want only the video, I think it just requires some margins around it so it doesn't fill the whole layout. That's just my opinion on it :)

**Comment by aeneasr** [comment]
Hello, can we get this proceed with this please? The video will at one point lose it's timeliness

**Comment by vinckr** [comment]
Its good to go imo, but the video starts in `720 automatic`, not`720p`. 
I looked everywhere, but it seems you cant force to start in 720p anymore :( 

> The getPlaybackQuality, setPlaybackQuality, and getAvailableQualityLevels functions are no longer supported. In particular, calls to setPlaybackQuality will be no-op functions, meaning they will not actually have any impact on the viewer's playback experience.

https://stackoverflow.com/questions/49223539/force-youtube-player-to-play-in-hd720-quality

I will commit the actual video and then mark ready for review.

**Comment by vinckr** [comment]
I'll reopen the PR.

**Pull request closed without merging**
