### PR TITLE
fix: typo in the code example

### PR DESCRIPTION
**Pull request by jfcurran**
fixed a typo in React Native blogpost code segment that called for ory instead of oryd

### CODE REVIEW

**Comment by aeneasr** [comment]
Ha, the URL is actually correct, I just haven't updated the template yet.

**Comment by aeneasr** [comment]
https://github.com/ory/kratos-selfservice-ui-react-native/commit/3dc18d91d93674785578724d1c9f724a201ef243

**Comment by aeneasr** [comment]
I pushed the package to npm, it should work now!

**Comment by tricky42** [comment]
Great and just to Johns defense I asked him to change the url to the one currently existing in npm ;) 

Quick question, on Docker Hub we use `oryd`, was `ory` already taken?

**Comment by aeneasr** [comment]
On Docker Hub it is not allowed to have 3 char org names :)

**Pull request closed without merging**
