### PR TITLE
chore: rework blog structure

### PR DESCRIPTION
**Pull request by zeropaper**
## Related Issue or Design Document

Based on ory-corp/marketing#5 

- [x] add ~~1~~ 3 "featured posts" to be shown on all the blog landing pages 
  - [x] with "hero" picture
  - [x] allow editing in CMS 
- [x] add a ~~filtering~~ navigation feature (by `tags`) above the posts list
  - [x] allow editing in CMS
  - [x] keep the browser vertically "locked" when navigating 
  - [x] create a landing page for each tag
- [x] add newsletter registration
- [x] publishing work to add tags, images and configuration

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

closes ory-corp/marketing#5 ory-corp/marketing#28

### CODE REVIEW

**Comment by zeropaper** [comment]
I didn't spend more than 10min on the actual styling.... 

image

**Comment by zeropaper** [comment]
@jfcurran I believe that this https://61ebae034855d87a1a235597--wonderful-sinoussi-8532a7.netlify.app/blog/tag/authentication#blog-tags

There's a bit more work to do on:

- tag page title
- layout / design of the featured posts
- active page link
- idea: "default image" / placeholder - when a blog post does not have an image?

image

your input would be welcome

**Comment by BlueAcidFrog** [comment]
@zeropaper, the different tags don't align properly - please display differently. 

Bildschirmfoto 2022-01-25 um 09 21 55

**Comment by zeropaper** [comment]
@BlueAcidFrog how about:
image

**Comment by zeropaper** [comment]
@BlueAcidFrog @jfcurran if you are cool with the current status, the only thing left to do is to add tags / categories to the content and adjust the list of "promoted tags" (something we could do together @BlueAcidFrog when you have 20min)

**Comment by BlueAcidFrog** [comment]
@zeropaper there seems to be a gray background underlying 
Bildschirmfoto 2022-01-25 um 09 21 55

Can we move the"never miss a patch" up below the three major please? I want to make it more visible  
Bildschirmfoto 2022-01-26 um 10 07 55

**Review by BlueAcidFrog — CHANGES_REQUESTED** [review]
Rework needed

**Comment by zeropaper** [comment]
> there seems to be a gray background underlying
@BlueAcidFrog nice catch.

Will move the newsletter form

**Comment by zeropaper** [comment]
@BlueAcidFrog 
https://user-images.githubusercontent.com/65971/151150178-d518aeaa-cabd-4789-a0ce-238078a09276.mp4

**Review by BlueAcidFrog — APPROVED** [review]

**Pull request merged**
