### PR TITLE
cms: create 'building slack bots using events api' blog post

### PR DESCRIPTION
**Pull request by zeropaper**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by vinckr — COMMENTED** [review]
@gen1us2k 
Very nice! 
I think you just need to add the stuff where you have a `//` comment and we do some editing and this is good to go 🎉 

I could add a "Outcome" or similar part too, where I describe what the effects of the bot have been after two weeks, but can also add that at a later point.

**Comment by gen1us2k** [comment]
@vinckr FYI. I moved the content here.

**Comment by vinckr** [comment]
I will review today 🙏

**Comment by vinckr** [comment]
sorry this is a mess, 
I reopened in https://github.com/ory/web/pull/572

**Pull request closed without merging**
