### PR TITLE
fix: add table styles to content generated from markdown

### PR DESCRIPTION
**Pull request by jfcurran**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments
added missing css classes for tables, table headers, rows and columns

### CODE REVIEW

**Comment by aeneasr** [comment]
Screenshot 2021-12-06 at 13 16 09

Content is right-bound instead of left bound

**Comment by jfcurran** [comment]
Screenshot 2021-12-06 at 13 32 10
I ran auto formatting before pushing and it messed with the alignment. its fixed again now

**Comment by jfcurran** [comment]
closes #460

**Comment by jfcurran** [comment]
closes #459

**Pull request merged**
