### PR TITLE
refactor: implement new design draft (#183)

### PR DESCRIPTION
**Pull request by aeneasr**
- [x] Fix all the links
- [x] Fix the paddings

### CODE REVIEW

**Comment by jfcurran** [comment]
[ ] 
[ ] 
[ ]

**Comment by Benehiko** [comment]
Related issue https://github.com/ory-corp/cloud/issues/786

**Comment by vinckr** [comment]
@jfcurran   @Benehiko 

- colour only changeable for one link

- navigation window not centered

- hero text not centered

- navigation fixed

- feature list weirdly responsive

- improve vertical rhythm

- Lighthouse

**Review by rafaelbmateus — APPROVED** [review]
Nice!

**Review by piotrmsc — APPROVED** [review]
LGTM for now, follow up is created by @vinckr

**Comment by zepatrik** [comment]
You guys removed all the `/next` and `/temp` stuff? There are no remnants of that left?

**Comment by vinckr** [comment]
@zepatrik 
Yes, it has all been moved into the main dir.

**Comment by zepatrik** [comment]
But the old content is still there? I don't think it is a good idea to have that still around as it might break SEO and UX if any link somewhere is pointing to old parts of the website. If it breaks the build then we actually have some dependency to the old page and it will definitely break SEO and UX, so fix it in that case. Please guys clean up after yourself. I will take a look tomorrow morning as I am OoO for the rest of the day.

**Comment by aeneasr** [comment]
WOW!

**Comment by aeneasr** [comment]
The mobile navigation is unfortunately not yet working properly. There is no visual differentiator between what's back and foreground. Also, I can scroll the navigation away!

Bildschirmfoto 2021-05-28 um 11 04 10

Bildschirmfoto 2021-05-28 um 11 04 00

**Comment by aeneasr** [comment]
Also, it looks like typography for paragraphs is not styled:

Bildschirmfoto 2021-05-28 um 11 06 08

Bildschirmfoto 2021-05-28 um 11 05 30

Current typography:

Bildschirmfoto 2021-05-28 um 11 10 16

Bildschirmfoto 2021-05-28 um 11 10 25

**Comment by jfcurran** [comment]
@aeneasr thank you very much for the detailed input - this is all being worked on in #205 and will be merged afterwards

**Pull request merged**
