### PR TITLE
ci: Delete outdated Netlify messages from PRs

### PR DESCRIPTION
**Pull request by kevgo**
The Netlify deploy preview feature posts a comment with links to Netlify. When making multiple commits, these messages accumulate and gunk up the discussion thread of the pull request. This change deletes all the previous messages when a new one is created. This means there will always be only one comment with Netlify links, pointing to the latest deploy.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by kevgo** [comment]
An example that and how this works is this PR. It contains many commits, each one  causing a Netlify deploy and notification in this thread. But the comment thread contains only one Netlify notification after the last commit!

**Review by vinckr — APPROVED** [review]
neat change! LGTM

**Comment by jfcurran** [comment]
Is there a case, where looking at old previews is beneficial? I once had the case where a preview build was failing or not working correctly, however an older version was. 

Maybe we can add something along the lines of

```
<details>
 <summary>Previous</summary>
 ...this is hidden, collapsable content...
</details>
```

so that the history is still accessible from within the PR.

@kevgo this is a neat change. I think my suggestion can be added in a different PR. Thank you 🚀

**Comment by vinckr** [comment]
>the case where a preview build was failing or not working correctly

I think if the build is failing it would not remove the old /add the next one, right?

**Pull request merged**
