### PR TITLE
feat: minor text changes

### PR DESCRIPTION
**Pull request by tacurran**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by jfcurran** [comment]
Thank You, @tacurran - Ill go over the changes

**Review by jfcurran — APPROVED** [review]
LGTM, ty vm

**Comment by aeneasr** [comment]
@jaredpreston you are tagged as a reviewer, blocking the merge. Please review the PR

**Review by jaredpreston — APPROVED** [review]

**Comment by aeneasr** [comment]
@jfcurran can you please address the merge conflicts?

https://www.jetbrains.com/help/idea/resolving-conflicts.html

**Pull request merged**
