### PR TITLE
feat: summit overview

### PR DESCRIPTION
**Pull request by MicLeey**
Adds a summit page with all sessions and a detail page for each.

### CODE REVIEW

**Comment by aeneasr** [comment]
Couldn’t find the page in the nav - maybe we should add it to the nav?

**Comment by BlueAcidFrog** [comment]
Under developer

**Comment by aeneasr** [comment]
where?  😅

67F29757-DAEB-494D-A5F5-B6EEB8665DBD

**Comment by BlueAcidFrog** [comment]
I meant to include the page into the section "developers" ☺️ @MicLeey

**Comment by jfcurran** [comment]
👏 nice work everybody 😌

**Pull request merged**
